[phases.setup]
nixPkgs = ["glib", "nss", "nspr", "atk", "cups", "dbus", "libdrm", "xorg.libXcomposite", "xorg.libXdamage", "xorg.libXrandr", "xorg.libxcb", "xorg.libX11", "mesa", "expat", "libxkbcommon", "gtk3", "pango", "cairo", "alsa-lib"]

[start]
cmd = "python bot.py"
